### PR TITLE
add the possibility to handle custom HTTP requests

### PR DESCRIPTION
**Pull request by mgallien**
modify KDSoapServerObjectInterface to add a new method to handle custom requests
modify KDSoapServerSocket to not reply when custom requests are handled

I am developping a library based on Qt5 and KDSoap to handle UPnP (https://gitlab.com/homeautomationqt/upnp-player-qt). In order to handle http and soap I am using KDSoap server and client implementations.

### CODE REVIEW

**Comment by mgallien** [comment]
Hello,
What can I do to move this pull request forward ?

I am especially interested to know if this is something that could be included in KDSoap. This way I could plan to find another way to achieve what I am doing with my patch.

Thanks in advance

**Comment by winterz** [comment]
Franck, Would you have time to review this pull request?

**Comment by mgallien** [comment]
Do you have time to review my last changes ?
Do you want me to merge some of the commits or are you ok with the branch as is ?

Thanks in advance

Best regards

**Comment by dfaure-kdab** [comment]
Oops sorry I thought I was still waiting for the unittests... I must have misparsed the notification when you added them. Reviewing now.

**Comment by mgallien** [comment]
Hello,

Sorry for the delay and the number of reviews necessary. Thanks for your patience.
I kept only two commits. I have made use of the "no if" approach. In fact, the test is simpler and I have learned something.

Best regards

**Comment by mgallien** [comment]
Hello David,

Thanks for having merged the pull request. Sorry for the warnings and the broken compilation.

Best regards

**Pull request merged**
