### PR TITLE
ignore CMake build folder

### PR DESCRIPTION
**Pull request by anoymouserver**
The directory is suggested here but not ignored by git..
https://github.com/KDAB/KDSoap/blob/dc4754f03aebb3201e61742c515df808f77471e6/INSTALL.txt#L19-L25

### CODE REVIEW

**Comment by winterz** [comment]
I don't think so.  how about your global $HOME/.gitignore?

**Comment by anoymouserver** [comment]
Yes it could. But if someone clones this repo and builds it as described in the INSTALL.txt, it should ignore the build results per default in my opinion. 🤔

**Comment by dfaure-kdab** [comment]
This makes sense to me, it's indeed consistent with the installation instructions. It's not like we have to ignore all possible names people might come up with (I have build_qt5_cmake, build_qt5_qmake, build_qt6 etc.) ;)
Allen: was that the basis for your objection?

**Comment by winterz** [comment]
no major objection.   I use "build" dirs in so many projects that it makes more sense to me to use global .gitignore

**Pull request merged**
